# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_info_mp3 <- function(filepath) {
    .Call(`_torchaudio_get_info_mp3`, filepath)
}

audiofile_read_wav_cpp <- function(filepath, from, to, unit) {
    .Call(`_torchaudio_audiofile_read_wav_cpp`, filepath, from, to, unit)
}

