name: Convert and upload pre-trained models

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - run: |
          python -m pip install --upgrade pip
          pip install torch google-cloud-storage

      - run: |
          python tools/convert-models.py
